[package]
name = "nodejs_path"
license = "MIT"
version = "0.0.1"
edition = "2021"
description = "Port path module of nodejs to rust using the same algorithms."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
